rabbitmq-host: rabbitmq
rabbitmq-port: 5672
rabbitmq-username: admin
rabbitmq-password: admin123

"%dev":
  rabbitmq-host: localhost

"%prod":
  rabbitmq-url: ${RABBITMQ_URL}
  mp:
    messaging:
      outgoing:
        identity-events-out:
          connector: smallrye-rabbitmq
          exchange:
            name: identity.events
            type: topic
            durable: true
          default-routing-key: "identity.#"
          connection-uri: ${RABBITMQ_URL}
        passenger-events-out:
          connector: smallrye-rabbitmq
          exchange:
            name: passenger.events
            type: topic
            durable: true
          default-routing-key: "passenger.#"
          connection-uri: ${RABBITMQ_URL}
        notification-events-out:
          connector: smallrye-rabbitmq
          exchange:
            name: notification.events
            type: topic
            durable: true
          default-routing-key: "notification.#"
          connection-uri: ${RABBITMQ_URL}

mp:
  messaging:
    outgoing:
      identity-events-out:
        connector: smallrye-rabbitmq
        exchange:
          name: identity.events
          type: topic
          durable: true
        default-routing-key: "identity.#"
      passenger-events-out:
        connector: smallrye-rabbitmq
        exchange:
          name: passenger.events
          type: topic
          durable: true
        default-routing-key: "passenger.#"
      notification-events-out:
        connector: smallrye-rabbitmq
        exchange:
          name: notification.events
          type: topic
          durable: true
        default-routing-key: "notification.#"
