quarkus:
  keycloak:
    admin-client:
      server-url: http://localhost:${keycloak.url:8080}

  log:
    level: ERROR

"%prod":
  quarkus:
    keycloak:
      admin-client:
        server-url: ${KEYCLOAK_INTERNAL_URL}
        realm: quarkus
        grant-type: client-credentials
        client-id: ${KEYCLOAK_ADMIN_CLIENT_ID:quarkus-admin-client}
        secret: ${KEYCLOAK_ADMIN_CLIENT_SECRET}
    http:
      client:
        connect-timeout: 30S
        idle-timeout: 5M
    rest-client:
      connect-timeout: 30S
