quarkus:
  keycloak:
    admin-client:
      server-url: http://localhost:${keycloak.url:8080}

  log:
    level: ERROR

"%prod":
  quarkus:
    keycloak:
      admin-client:
        server-url: ${KEYCLOAK_INTERNAL_URL}
        realm: master
        grant-type: password
        username: admin
        password: ${KEYCLOAK_ADMIN_PASSWORD}
    http:
      client:
        connect-timeout: 30S
        idle-timeout: 5M
    rest-client:
      connect-timeout: 30S
