services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.4.2
    volumes:
      - ../keycloak/providers:/opt/keycloak/providers:ro
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_HEALTH_ENABLED: "true"
      KC_HTTP_MANAGEMENT_PORT: 9000
    ports:
      - "8080"
    labels:
      io.quarkus.devservices.compose.config_map.port.8080: keycloak.url
    command: start-dev
    healthcheck:
      test: ["CMD-SHELL", "bash -c ':> /dev/tcp/localhost/9000'"]
      interval: 5s
      timeout: 3s
      retries: 30
      start_period: 30s

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    ports:
      - "5432"
    labels:
      io.quarkus.devservices.compose.config_map.port.5432: quarkus.datasource.jdbc.port
